config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  resources :equipamentos
  get 'sac/inadimplencia'
  get 'sac/suspensao'
  resources :nfcom_notas, only: [:show] 
  resources :atendimento_detalhes, only: %i[new create index]
  resources :atendimentos do
    get :encerrar, on: :member
  end
  resources :os do
    get :impressao, on: :member
  end
  resources :classificacoes
  resources :clasificacoes
  resources :excecoes
  resources :ip_redes
  resources :nf21s, only: %i[show]
  resources :nf21s do
    get 'competencia/:mes', action: :competencia, as: :competencia, on: :collection
  end
  resources :fibra_caixas
  resources :fibra_redes
  resources :retornos
  resources :pagamento_perfis do
    get 'remessa/:sequencia', action: :remessa, as: :remessa, on: :member
  end
  resources :liquidacoes
  resources :faturas do
    get :liquidacao, on: :member
    get :boleto, on: :member
    get :estornar, on: :member
    get :cancelar, on: :member
    get :gerar_nf, on: :member
  end
  patch '/contratos/:id/assinatura' => 'contratos#update_assinatura'
  resources :contratos do
    get :boletos, on: :member
    get :renovar, on: :member
    get :termo, on: :member
    get :churn, on: :collection
    get :assinatura, on: :member
    get :autentique, on: :member
    get :pendencias, on: :collection
  end
  resources :conexoes do
    get :suspenso, on: :collection
    get :integrar, on: :collection
  end
  resources :pessoas do
    get :autocomplete_logradouro_nome, on: :collection
  end
  resources :plano_enviar_atributos
  resources :plano_verificar_atributos
  resources :pontos do
    get :snmp, on: :collection
  end
  resources :planos
  resources :servidores do
    get :backup, on: :member
    get :backups, on: :collection
    get :mapa, on: :member
  end
  resources :logradouros
  resources :bairros
  resources :cidades do
    get :sici, on: :collection
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :estados
  resources :token
  resources :settings
  post '/webhooks/:token' => 'webhook_eventos#create'
  get 'welcome/index'
  root 'welcome#index'
end

app/controllers/liquidacoes_controller.rb
# frozen_string_literal: true

class LiquidacoesController < ApplicationController
  load_and_authorize_resource :fatura, through: :liquidacoes

  def index
    @liquidacoes = Fatura.select('count(*) as liquidacoes, sum(valor_liquidacao) as valor')
                         .where('not liquidacao is null')
    if params.key?(:mes)
      @liquidacoes = @liquidacoes.select('extract(month from liquidacao)::int as mes')
                                 .where('extract(year from liquidacao) = ?', params[:ano])
                                 .group('extract(month from liquidacao)')
                                 .order(:mes)
      @chart = Fatura.where('extract(year from liquidacao) = ?', params[:ano])
                     .group('extract(month from liquidacao)')
                     .sum(:valor_liquidacao)
    elsif params.key?(:ano)
      @liquidacoes = @liquidacoes.select('extract(year from liquidacao)::int as ano')
                                 .group('extract(year from liquidacao)')
                                 .order(:ano)
      @chart = Fatura.where.not(liquidacao: nil)
                     .group('extract(year from liquidacao)')
                     .order('extract(year from liquidacao)')
                     .sum(:valor_liquidacao)
    else
      @liquidacoes = @liquidacoes.select('liquidacao as data').group(:liquidacao).order(liquidacao: :desc)
    end
    @liquidacoes.page params[:page]
  end

  def show
    @liquidacoes = Fatura.includes([:contrato, :pessoa]).where('liquidacao = ?', params[:id])
    @liquidacoes = @liquidacoes.where('meio_liquidacao = ?', params[:meio]) if params.key?(:meio)
    @liquidacoes = @liquidacoes.page params[:page]
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def liquidacoes_params
    params.permit(:mes, :ano)
  end
end

app/helpers/liquidacoes_helper.rb
# frozen_string_literal: true

module LiquidacoesHelper
end

app/views/liquidacoes/index.html.slim
.card
  = render '/shared/table_header', {object: @liquidacoes, titulo: "Liquidações"}
  .card-body
    = column_chart @chart
    .table-responsive
      table.table.table-striped
        thead
          tr
            - if params.key?(:mes)
              th
                | Mês
            - elsif params.key?(:ano)
              th
                | Ano
            - else
              th
                | Data
            th.text-center
              | Pagamentos
            th.text-right
              | Valor Total
        tbody
          - @liquidacoes.each do |liquidacao|
            tr
              - if params.key?(:mes)
                td
                  = link_to Date::MONTHNAMES[liquidacao.mes], liquidacao_path(liquidacao.mes)
              - elsif params.key?(:ano)
                td
                  = link_to liquidacao.ano, liquidacoes_path(ano: liquidacao.ano, mes: 1)
              - else
                td
                  = link_to l(liquidacao.data.to_date), liquidacao_path(liquidacao.data)
              td.text-center
                = number_with_delimiter(liquidacao.liquidacoes)
              td.text-right
                = number_to_currency(liquidacao.valor)
      - #paginate @liquidacoes
.card

app/views/liquidacoes/show.html.slim
.card
  = render '/shared/table_header', {object: @liquidacoes, titulo: "Liquidações "+l(params[:id].to_date) }
  .card-body
    .table-responsive
      table.table.table-striped
        thead
          tr
            th
              | Assinante
            th
              | Contrato
            th
              | Parcela
            th
              | Forma de Pagamento
            th
              | Valor
            th
              | Vencimento
        tbody
          - @liquidacoes.each do |liquidacao|
            tr
              td
                = link_to liquidacao.contrato.pessoa.nome, liquidacao.contrato.pessoa
              td
                = link_to liquidacao.contrato.id, liquidacao.contrato
              td
                = link_to liquidacao.parcela, liquidacao
              td
                = liquidacao.meio_liquidacao
              td
                = number_to_currency(liquidacao.valor_liquidacao)
              td
                = l(liquidacao.vencimento)
      = paginate @liquidacoes