config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  resources :equipamentos
  get 'sac/inadimplencia'
  get 'sac/suspensao'
  resources :nfcom_notas, only: [:show] 
  resources :atendimento_detalhes, only: %i[new create index]
  resources :atendimentos do
    get :encerrar, on: :member
  end
  resources :os do
    get :impressao, on: :member
  end
  resources :classificacoes
  resources :clasificacoes
  resources :excecoes
  resources :ip_redes
  resources :nf21s, only: %i[show]
  resources :nf21s do
    get 'competencia/:mes', action: :competencia, as: :competencia, on: :collection
  end
  resources :fibra_caixas
  resources :fibra_redes
  resources :retornos
  resources :pagamento_perfis do
    get 'remessa/:sequencia', action: :remessa, as: :remessa, on: :member
  end
  resources :liquidacoes
  resources :faturas do
    get :liquidacao, on: :member
    get :boleto, on: :member
    get :estornar, on: :member
    get :cancelar, on: :member
    get :gerar_nf, on: :member
  end
  patch '/contratos/:id/assinatura' => 'contratos#update_assinatura'
  resources :contratos do
    get :boletos, on: :member
    get :renovar, on: :member
    get :termo, on: :member
    get :churn, on: :collection
    get :assinatura, on: :member
    get :autentique, on: :member
    get :pendencias, on: :collection
  end
  resources :conexoes do
    get :suspenso, on: :collection
    get :integrar, on: :collection
  end
  resources :pessoas do
    get :autocomplete_logradouro_nome, on: :collection
  end
  resources :plano_enviar_atributos
  resources :plano_verificar_atributos
  resources :pontos do
    get :snmp, on: :collection
  end
  resources :planos
  resources :servidores do
    get :backup, on: :member
    get :backups, on: :collection
    get :mapa, on: :member
  end
  resources :logradouros
  resources :bairros
  resources :cidades do
    get :sici, on: :collection
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :estados
  resources :token
  resources :settings
  post '/webhooks/:token' => 'webhook_eventos#create'
  get 'welcome/index'
  root 'welcome#index'
end

app/models/retorno.rb
# frozen_string_literal: true

require 'cobranca/retorno_240'
require 'cobranca/retorno_400'
require 'cobranca/bb_400'

class Retorno < ApplicationRecord
  belongs_to :pagamento_perfil
  has_many :faturas, dependent: :restrict_with_exception
  has_many :registros,
           class_name: :Fatura,
           foreign_key: :registro_id,
           dependent: :restrict_with_exception,
           inverse_of: :registro
  has_many :baixas,
           class_name: :Fatura,
           foreign_key: :baixa_id,
           dependent: :restrict_with_exception,
           inverse_of: :baixa
  has_one_attached :arquivo

  ARQUIVO_COMPATIVEL = 'Arquivo não é compatível com o convênio selecionado'

  def verificar_header
    case pagamento_perfil.tipo
    when 'Boleto'
      data_file = File.open(
        ActiveStorage::Blob.service.send(:path_for, arquivo.key)
      )
      case pagamento_perfil.banco
      when 33
        header = Retorno240Header.load_line data_file.first
        raise StandardError.new, ARQUIVO_COMPATIVEL unless header.convenio.to_i == pagamento_perfil.cedente

        self.attributes = {
          sequencia: header.sequencia,
          data: cnab_to_date(header.data)
        }
        save
      when 1
        header = Retorno400Header.load_line data_file.first
        unless header.retorno.to_i == 2 && header.tipo.to_i == 1 && header.convenio.to_i == pagamento_perfil.cedente
          raise StandardError.new, ARQUIVO_COMPATIVEL
        end

        self.attributes = {
          sequencia: header.sequencia,
          data: cnab_to_date(header.data)
        }
        save
      end
    when 'Débito Automático'
    end
  end

  def processar
    verificar_header
    carregar_arquivo.each do |linha|
      next unless linha.data_ocorrencia.to_i.positive?

      fatura = Fatura.find_by(
        pagamento_perfil: pagamento_perfil,
        nossonumero: cnab_to_nosso_numero(linha.nosso_numero)
      )
      next if fatura.blank?
      # instrucao rejeitada
      next if linha.codigo_ocorrencia.to_i == 26

      case linha.codigo_ocorrencia.to_i
      when 6
        # titulo liquidado
        desconto = [0, cnab_to_float(linha.valor_recebido) - fatura.valor].min
        fatura.attributes = {
          liquidacao: cnab_to_date(linha.data_ocorrencia),
          juros_recebidos: cnab_to_float(linha.juros_mora),
          banco: linha.banco_recebedor,
          desconto_concedido: desconto,
          agencia: linha.agencia_recebedora_com_dv[0...-1],
          valor_liquidacao: cnab_to_float(linha.valor_recebido),
          meio_liquidacao: :RetornoBancario,
          retorno: self
        }
      when 2
        # titulo registrado
        fatura.attributes = {
          registro: self
        }
      when 9, 10
        # titulo baixado manualmente
        fatura.attributes = {
          baixa: self
        }
      end
      fatura.save
    end
    SuspensaoAutomaticaJob.perform_later if pode_supsender?
  end

  def carregar_arquivo
    case pagamento_perfil.banco
    when 33
      Brcobranca::Retorno::Cnab240::Santander.load_lines(
        ActiveStorage::Blob.service.send(:path_for, arquivo.key)
      )
    when 1
      Brcobranca::Retorno::Cnab400::BB.load_lines(
        ActiveStorage::Blob.service.send(:path_for, arquivo.key)
      )
    end
  end

  def cnab_to_float(valor)
    valor.to_f / 100
  end

  def cnab_to_currency(valor)
    number_to_currency(valor.to_f / 100)
  end

  def cnab_to_date(valor)
    if valor.length == 8
      Date.strptime(valor, '%d%m%Y')
    else
      Date.strptime(valor, '%d%m%y')
    end
  end

  def cnab_to_nosso_numero(valor)
    case pagamento_perfil.banco
    when 33
      # remove leading zeros and trailing digit
      valor.sub!(/^0+/, '')[0...-1]
    when 1
      valor[7..].sub(/^0+/, '')
    end
  end

  private

  def pode_suspender?
    Retorno.where(data: Time.zone.today - 1.day).count >= 2
  end
end

app/controllers/retornos_controller.rb
# frozen_string_literal: true

class RetornosController < ApplicationController
  load_and_authorize_resource
  before_action :set_retorno, only: %i[show edit update destroy]

  # GET /retornos
  # GET /retornos.json
  def index
    @q = Retorno.joins(:pagamento_perfil).where.not(pagamento_perfis: {banco: 364}).ransack(params[:q])
    @q.sorts = 'data desc'
    @retornos = @q.result.page params[:page]
  end

  # GET /retornos/1
  # GET /retornos/1.json
  def show
    @faturas = Fatura.where(pagamento_perfil: @retorno.pagamento_perfil)
    @linhas = @retorno.carregar_arquivo
  end

  # GET /retornos/new
  def new
    @retorno = Retorno.new
  end

  # GET /retornos/1/edit
  def edit; end

  # POST /retornos
  # POST /retornos.json
  def create
    @retorno = Retorno.new(retorno_params)

    respond_to do |format|
      if @retorno.save
        format.html { redirect_to @retorno, notice: 'Retorno was successfully created.' }
        format.json { render :show, status: :created, location: @retorno }
      else
        format.html { render :new }
        format.json { render json: @retorno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /retornos/1
  # PATCH/PUT /retornos/1.json
  def update
    @retorno.processar
    respond_to do |format|
      format.html { redirect_to @retorno, notice: 'Retorno was successfully updated.' }
      format.json { render :show, status: :ok, location: @retorno }
    end
  rescue StandardError => e
    respond_to do |format|
      format.html { redirect_to @retorno, notice: e.message }
      format.json { render :show, status: :ok, location: @retorno }
    end
  end

  # DELETE /retornos/1
  # DELETE /retornos/1.json
  def destroy
    @retorno.destroy
    respond_to do |format|
      format.html { redirect_to retornos_url, notice: 'Retorno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_retorno
    @retorno = Retorno.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def retorno_params
    params.require(:retorno).permit(:pagamento_perfil_id, :data, :sequencia, :arquivo)
  end
end

app/helpers/retornos_helper.rb
# frozen_string_literal: true

module RetornosHelper
  def cnab_to_float(s)
    s.to_f / 100
  end

  def cnab_to_currency(s)
    number_to_currency(s.to_f / 100)
  end

  def cnab_to_date(s)
    Date.strptime(s, '%d%m%y')
  end

  def cnab_to_nosso_numero_santander(s)
    # remove leading zeros and trailing digit
    s.sub!(/^0+/, '')[0...-1]
  end

  def cnab_to_nosso_numero_bb(s)
    s[10..-1].sub!(/^0+/, '')
  end
end

app/views/retornos/_form.html.erb
<%= simple_form_for(@retorno) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-inputs">
    <%= f.association :pagamento_perfil, label_method: :nome %>
    <%= f.input :arquivo, as: :file %>
  </div>

  <div class="actions">
    <%= button_tag(:class => "btn btn-primary") do %>
      <i class="fas fa-save" aria-hidden="true"></i> Salvar
    <% end %>
  </div>
<% end %>

app/views/retornos/_table.html.erb
<div class="card">
  <%= render '/shared/table_header', {object: @retornos, titulo: "Retorno Bancário", search_string: :pagamento_perfil_nome_cont} %>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Perfil</th>
            <th>Data</th>
            <th>Sequência</th>
            <th>Liquidações</th>
            <th>Registros</th>
            <th>Baixas</th>
         </tr>
        </thead>

        <tbody>
          <% @retornos.each do |retorno| %>
            <tr>
              <td><%= link_to retorno.pagamento_perfil.nome, retorno.pagamento_perfil %></td>
              <td><%= link_to l(retorno.data, default: 'Sem data'), retorno %></td>
              <td><%= retorno.sequencia %></td>
              <td><%= retorno.faturas.count %>
              <td><%= retorno.registros.count %>
              <td><%= retorno.baixas.count %>
           </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= paginate @retornos %>
</div>

app/views/retornos/edit.html.erb
<div class="card">
  <%= render 'shared/edit_header', {object: @retorno, titulo: "Retorno Bancário"} %>
  <div class="card-body">
    <%= render 'form', retorno: @retorno %>
  </div>
</div>

app/views/retornos/index.html.erb
<%= render 'table', retornos: @retornos %>

app/views/retornos/new.html.erb
<div class="card">
  <%= render "shared/new_header", { object: @retorno, titulo: "Retorno Bancário" } %>
  <div class="card-body">
    <%= render "form" %>
  </div>
</div>

app/views/retornos/show.html.erb
<div class="card">
  <%= render 'shared/show_header', {object: @retorno, titulo: "Retorno Bancário"} %>
  <div class="card-body">
    <div class="card-columns" style="column-count: 4">
      <%= render 'shared/field_card', {campo: "Perfil", valor: @retorno.pagamento_perfil.nome} %>
      <%= render 'shared/field_card', {campo: "Data", valor: l(@retorno.data, default: '')} %>
      <%= render 'shared/field_card', {campo: "Sequência", valor: @retorno.sequencia} %>
    </div>

    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Nosso Número</th>
            <th>Ocorrência</th>
            <th>Pagamento</th>
            <th>Vencimento</th>
            <th>Valor Título</th>
            <th>Juros</th>
            <th>Desconto</th>
            <th>Recebido</th>
            <th>Banco</th>
            <th>Agência</th>
         </tr>
        </thead>

        <tbody>
          <% (@linhas || []).each do |linha| %>
            <% if linha.data_vencimento.to_i > 0 %>
              <tr>
                <td>
                  <% nossonumero = @retorno.pagamento_perfil.banco == 33 ? cnab_to_nosso_numero_santander(linha.nosso_numero) : cnab_to_nosso_numero_bb(linha.nosso_numero) %>
                  <%= link_to faturas_path q: {nossonumero_eq: nossonumero}, target: "_blank" do %>
                    <%= nossonumero %>
                  <% end %>
                </td>
                <td><%= linha.codigo_ocorrencia %></td>
                <td><%= l(cnab_to_date(linha.data_ocorrencia)) %></td>
                <td><%= l(cnab_to_date(linha.data_vencimento)) %></td>
                <td><%= cnab_to_currency(linha.valor_titulo) %></td>
                <td><%= cnab_to_currency(linha.juros_mora) %></td>
                <td><%= cnab_to_currency(linha.desconto_concedito) %></td>
                <td><%= cnab_to_currency(linha.valor_recebido) %></td>
                <td><%= linha.banco_recebedor %></td>
                <td><%= linha.agencia_recebedora_com_dv %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
<%= simple_form_for(@retorno) do |f| %>
  <div class="actions">
    <%= button_tag(:class => "btn btn-primary") do %>
      <i class="fas fa-save" aria-hidden="true"></i> Processar
    <% end %>
  </div>
<% end %>

</div>
</div>