config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  resources :equipamentos
  get 'sac/inadimplencia'
  get 'sac/suspensao'
  resources :nfcom_notas, only: [:show] 
  resources :atendimento_detalhes, only: %i[new create index]
  resources :atendimentos do
    get :encerrar, on: :member
  end
  resources :os do
    get :impressao, on: :member
  end
  resources :classificacoes
  resources :clasificacoes
  resources :excecoes
  resources :ip_redes
  resources :nf21s, only: %i[show]
  resources :nf21s do
    get 'competencia/:mes', action: :competencia, as: :competencia, on: :collection
  end
  resources :fibra_caixas
  resources :fibra_redes
  resources :retornos
  resources :pagamento_perfis do
    get 'remessa/:sequencia', action: :remessa, as: :remessa, on: :member
  end
  resources :liquidacoes
  resources :faturas do
    get :liquidacao, on: :member
    get :boleto, on: :member
    get :estornar, on: :member
    get :cancelar, on: :member
    get :gerar_nf, on: :member
  end
  patch '/contratos/:id/assinatura' => 'contratos#update_assinatura'
  resources :contratos do
    get :boletos, on: :member
    get :renovar, on: :member
    get :termo, on: :member
    get :churn, on: :collection
    get :assinatura, on: :member
    get :autentique, on: :member
    get :pendencias, on: :collection
  end
  resources :conexoes do
    get :suspenso, on: :collection
    get :integrar, on: :collection
  end
  resources :pessoas do
    get :autocomplete_logradouro_nome, on: :collection
  end
  resources :plano_enviar_atributos
  resources :plano_verificar_atributos
  resources :pontos do
    get :snmp, on: :collection
  end
  resources :planos
  resources :servidores do
    get :backup, on: :member
    get :backups, on: :collection
    get :mapa, on: :member
  end
  resources :logradouros
  resources :bairros
  resources :cidades do
    get :sici, on: :collection
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :estados
  resources :token
  resources :settings
  post '/webhooks/:token' => 'webhook_eventos#create'
  get 'welcome/index'
  root 'welcome#index'
end

app/models/estado.rb
# frozen_string_literal: true

class Estado < ApplicationRecord
  require 'csv'
  has_many :cidades

  def titulo
    'Estado'
  end

  def search
    'nome_cont'
  end

  def self.to_csv
    attributes = %w[id sigla nome ibge]
    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |estado|
        csv << attributes.map { |attr| estado.send(attr) }
      end
    end
  end
end

app/controllers/estados_controller.rb
# frozen_string_literal: true

class EstadosController < ApplicationController
  load_and_authorize_resource
  before_action :set_estado, only: %i[show edit update destroy]

  # GET /estados
  # GET /estados.json
  def index
    @q = Estado.ransack(params[:q])
    @estados = @q.result(order: :nome).page params[:page]
    respond_to do |format|
      format.html
      format.csv { send_data @estados.except(:limit, :offset).to_csv, filename: "estados-#{Date.today}.csv" }
    end
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
    @estado = Estado.find(params[:id])
    @q = @estado.cidades.ransack(params[:q])
    @q.sorts = 'nome'
    @cidades = @q.result.page params[:page]
  end

  # GET /estados/new
  def new
    @estado = Estado.new
  end

  # GET /estados/1/edit
  def edit; end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(estado_params)

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado criado com sucesso.' }
        format.json { render :show, status: :created, location: @estado }
      else
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estados/1
  # PATCH/PUT /estados/1.json
  def update
    respond_to do |format|
      if @estado.update(estado_params)
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { render :show, status: :ok, location: @estado }
      else
        format.html { render :edit }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado.destroy
    respond_to do |format|
      format.html { redirect_to estados_url, notice: 'Estado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_estado
    @estado = Estado.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def estado_params
    params.require(:estado).permit(:sigla, :nome, :ibge)
  end
end

app/helpers/estados_helper.rb
# frozen_string_literal: true

module EstadosHelper
end

app/views/estados/_form.html.erb
<%= form_for @estado do |form| %>
  <% if estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estado.errors.count, "error") %> prohibited this estado from being saved:</h2>

      <ul>
      <% estado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :sigla %>
    <%= form.text_field :sigla, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :nome %>
    <%= form.text_field :nome, class: "form-control"%>
  </div>

  <div class="from-group">
    <%= form.label :ibge %>
    <%= form.number_field :ibge, class: "form-control" %>
  </div>

  <div class="actions">
    <%= button_tag( :class => "btn btn-primary") do %>
      <i class="fas fa-save" aria-hidden="true"></i> Salvar
    <% end %>
  </div>
<% end %>

app/views/estados/edit.html.erb
<div class="card">
  <%= render 'shared/edit_header', {object: @estado, titulo: "Estado"} %>
  <div class="card-body">
    <%= render 'form', estado: @estado %>
  </div>
</div>

app/views/estados/index.html.erb
<div class="card">
  <%= render '/shared/table_header', {object: @estados, search_string: :sigla_or_nome_cont} %>
  <div class="card-body">
  <div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Sigla</th>
        <th>Nome</th>
        <th>IBGE</th>
      </tr>
    </thead>
  
    <tbody>
      <% @estados.each do |estado| %>
        <tr>
          <td><%= estado.sigla %></td>
          <td><%= link_to estado.nome, estado %></td>
          <td><%= estado.ibge %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @estados %>
  </div>
  </div>
</div>

app/views/estados/new.html.erb
<h1>Criar Estado</h1>

<%= render 'form', estado: @estado %>

<%= link_to 'Back', estados_path %>

app/views/estados/show.html.erb
<div class="card">
  <%= render 'shared/show_header', {object: @estado} %>
  <div class="card-body">
    <div class="card-columns" style="column-count: 4">
      <%= render 'shared/field_card', {campo: "Sigla", valor: @estado.sigla} %>
      <%= render 'shared/field_card', {campo: "IBGE", valor: @estado.ibge} %>
    </div>
  </div>
</div>
<div class="card">
  <%= render 'cidades/table', cidades: @cidades %>
</div>