config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  resources :equipamentos
  get 'sac/inadimplencia'
  get 'sac/suspensao'
  resources :nfcom_notas, only: [:show] 
  resources :atendimento_detalhes, only: %i[new create index]
  resources :atendimentos do
    get :encerrar, on: :member
  end
  resources :os do
    get :impressao, on: :member
  end
  resources :classificacoes
  resources :clasificacoes
  resources :excecoes
  resources :ip_redes
  resources :nf21s, only: %i[show]
  resources :nf21s do
    get 'competencia/:mes', action: :competencia, as: :competencia, on: :collection
  end
  resources :fibra_caixas
  resources :fibra_redes
  resources :retornos
  resources :pagamento_perfis do
    get 'remessa/:sequencia', action: :remessa, as: :remessa, on: :member
  end
  resources :liquidacoes
  resources :faturas do
    get :liquidacao, on: :member
    get :boleto, on: :member
    get :estornar, on: :member
    get :cancelar, on: :member
    get :gerar_nf, on: :member
  end
  patch '/contratos/:id/assinatura' => 'contratos#update_assinatura'
  resources :contratos do
    get :boletos, on: :member
    get :renovar, on: :member
    get :termo, on: :member
    get :churn, on: :collection
    get :assinatura, on: :member
    get :autentique, on: :member
    get :pendencias, on: :collection
  end
  resources :conexoes do
    get :suspenso, on: :collection
    get :integrar, on: :collection
  end
  resources :pessoas do
    get :autocomplete_logradouro_nome, on: :collection
  end
  resources :plano_enviar_atributos
  resources :plano_verificar_atributos
  resources :pontos do
    get :snmp, on: :collection
  end
  resources :planos
  resources :servidores do
    get :backup, on: :member
    get :backups, on: :collection
    get :mapa, on: :member
  end
  resources :logradouros
  resources :bairros
  resources :cidades do
    get :sici, on: :collection
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :estados
  resources :token
  resources :settings
  post '/webhooks/:token' => 'webhook_eventos#create'
  get 'welcome/index'
  root 'welcome#index'
end

app/models/bairro.rb
# frozen_string_literal: true

require 'csv'

class Bairro < ApplicationRecord
  belongs_to :cidade
  has_one :estado, through: :cidade
  has_many :logradouros
  has_many :assinantes,
           -> { assinantes },
           source: :pessoas,
           through: :logradouros

  has_many :conexoes, through: :assinantes
  geocoded_by :nome_cidade_uf
  after_validation :geocode

  def nome_cidade_uf
    "#{nome} - #{cidade.nome_uf}"
  end
end

app/controllers/bairros_controller.rb
# frozen_string_literal: true

class BairrosController < ApplicationController
  include ConexoesHelper

  before_action :set_bairro, only: %i[show edit update destroy]
  load_and_authorize_resource

  # GET /bairros
  # GET /bairros.json
  def index
    @q = Bairro.ransack(params[:q])
    @bairros = @q.result(order: :nome).page params[:bairros_page]
    respond_to do |format|
      format.html
      format.csv { send_data @bairros.except(:limit, :offset).to_csv, filename: "bairros-#{Date.today}.csv" }
    end
    @params = {}
  end

  # GET /bairros/1
  # GET /bairros/1.json
  def show
    @bairro = Bairro.find(params[:id])
    @q = @bairro.logradouros.ransack(params[:q])
    @q.sorts = 'nome'
    @logradouros = @q.result.page params[:logradouros_page]
    @conexao_q = @bairro.conexoes.ransack(params[:conexao_q])
    @conexao_q.sorts = 'ip'
    @conexoes = @conexao_q.result.page params[:conexoes_page]
    @params = conexoes_params(params)
  end

  # GET /bairros/new
  def new
    @bairro = Bairro.includes(:cidades, :estados).new
  end

  # GET /bairros/1/edit
  def edit; end

  # POST /bairros
  # POST /bairros.json
  def create
    @bairro = Bairro.new(bairro_params)

    respond_to do |format|
      if @bairro.save
        format.html { redirect_to @bairro, notice: 'Bairro criado com sucesso.' }
        format.json { render :show, status: :created, location: @bairro }
      else
        format.html { render :new }
        format.json { render json: @bairro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bairros/1
  # PATCH/PUT /bairros/1.json
  def update
    respond_to do |format|
      if @bairro.update(bairro_params)
        format.html { redirect_to @bairro, notice: 'Bairro atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @bairro }
      else
        format.html { render :edit }
        format.json { render json: @bairro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bairros/1
  # DELETE /bairros/1.json
  def destroy
    @bairro.destroy
    respond_to do |format|
      format.html { redirect_to bairros_url, notice: 'Bairro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bairro
    @bairro = Bairro.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bairro_params
    params.require(:bairro).permit(:nome, :cidade_id, :latitude, :longitude)
  end
end

app/helpers/bairros_helper.rb
# frozen_string_literal: true

module BairrosHelper
end

app/views/bairros/_form.html.slim
= simple_form_for(@bairro) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs
    = f.input :nome
    = f.association :cidade, label_method: :nome_uf
    = f.input :latitude
    = f.input :longitude
  .form-actions
    = button_tag(:class => "btn btn-primary") do
      i.fas.fa-save aria-hidden="true" 
      | &nbsp; Salvar

app/views/bairros/_table.html.slim
.card
  = render '/shared/table_header', { object: @bairros, search_string: :nome_cont }
  .card-body
    .table-responsive
      table.table.table-striped
        thead
          tr
            th Nome
            th Cidade
            th Assinantes
            th Latitude
            th Longitude
        tbody
          - @bairros.each do |bairro|
            tr
              td = link_to bairro.nome, bairro
              td = bairro.cidade.nome_uf
              td align="center" = bairro.assinantes.size
              td align="center" = bairro.latitude
              td align="center" = bairro.longitude
    = paginate @bairros, params: @params.merge({tab: "bairros"}), param_name: "bairros_page"

app/views/bairros/edit.html.slim
.card
  = render 'shared/edit_header', { object: @bairro, titulo: 'Bairro' }
  .card-body
    = render 'form', bairro: @bairro

app/views/bairros/index.html.slim
= render 'table', bairros: @bairros

app/views/bairros/new.html.erb
<h1>New Bairro</h1>

<%= render 'form', bairro: @bairro %>

<%= link_to 'Back', bairros_path %>

app/views/bairros/show.html.slim
ul.nav.nav-pills
  li.nav-item
    a.nav-link class="#{params.key?(:conexao_q) ? '' : 'active'}" data-toggle='tab' href='#bairro' Bairro
  li.nav-item
    a.nav-link class="#{params.key?(:conexao_q) ? 'active' : ''}" data-toggle='tab' href='#conexoes' Conexões
.tab-content
  #bairro.tab-pane.fade aria-labelledby='bairro-tab' class="#{params.key?(:conexao_q) ? '' : 'show active'}" role='tabpanel'
    .row
      .card.col-sm
        = render 'shared/show_header', { object: @bairro }
        .card-body
          .card-columns style='column-count: 3'
            = link_to @bairro.cidade do
              = render 'shared/field_card', { campo: 'Cidade', valor: @bairro.cidade.nome_uf }
            = render 'shared/field_card', { campo: 'Latitude', valor: @bairro.latitude }
            = render 'shared/field_card', { campo: 'Longitude', valor: @bairro.longitude }
      .card.col-sm
        p align='center'
          = image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=16&size=400x300&center=#{@bairro.latitude},#{@bairro.longitude}&key=#{Rails.application.credentials.google_maps_api_key}", alt: 'Map'
    .row
      .card.col-sm
        = render 'logradouros/table', params: { bairro_id: @bairro }
  #conexoes.tab-pane.fade aria-labelledby='conexoes-tab' class="#{params.key?(:conexao_q) ? 'show active' : ''}" role='tabpanel'
    .row
      h3 = @bairro.nome
      = render 'conexoes/table', { exclude: ['equipamento'], custom_q: @conexoes_q }